### ISSUE TITLE
[BUG] Fails to launch GtkWindow sometimes after hot reload

### ISSUE THREAD

**Issue by codyduong** [codyduong/hitokage#59]
**Expected behavior**
On hot-reload after modifying `init.lua` there is a chance for it to fail.

** Environment **

- windows version: 10.0.22631.0
- _hitokage_ version: aa1a7b41af05a77bd6404655c74cbf9e503c8ebb

`init.lua`
```lua
local monitors = hitokage.monitor.get_all()

for _, monitor in ipairs(monitors) do
	monitor:attach({
		children = {
			{ Workspace = { halign = "Start", item_height = 24, item_width = 24 } },
			{ Box = {} },
			{ Clock = { format = "%a %b %u %r", halign = "End" } },
		},
		homogeneous = true,
	})
end

```

`styles.css`
```css
window {
  /* Be careful about setting values here, this also modifies the debugger appearance */
  font-family: 'MesloLGS Nerd Font Mono', 'Courier New', 'Bars', 'Font Awesome 5 Free';
  font-size: 12px;
  color: #000000;
}

.bar {
  background-color: rgba(29, 32, 33, 1.0);
  color: #f2e5bc;
  
  font-family: 'MesloLGS NF', 'Courier New', 'Bars', 'Font Awesome 5 Free';
  font-size: 14px;
  line-height: 14px;
  padding-left: 8px;
  padding-right: 8px;
}

.workspace {
  padding: 0px 0px 0px 0px;
  /* border: 1px solid rgba(255, 0, 0, 0.4); */
}

.workspacechild {
  /* distance between workspace children */
  /* margin-left: 8px; */
  border: 1px solid rgba(168, 153, 132, 0.4);

  color: #f2e5bc;
  background-color: rgba(60, 56, 54, 0.4);

  font-size: 11px;
  /* border-radius: 11px; */

  transition: all 500ms;
  transition-property: min-width, background-color;
}

.workspacechild:first-child {
  margin-left: 0px;
}

.workspacechild:selected {
  /* min-width: 32px; */
  border: 1px solid #f2e5bc;
  background-color: #f2e5bc;
  color: #333333;
  font-weight: bold;
}
```
