### ISSUE TITLE
[BUG] Issue using without Komorebi

### ISSUE THREAD

**Issue by TetraTsunami** [codyduong/hitokage#60]
## Expected behavior
I expected Hitokage to function without Komorebi running, based on this line from the top of the README.md:
> It is primarily built for usage with komorebi, but is also usable as a standalone drop-in replacement for the default Windows Taskbar.

## Environment

- windows version: 10.0.26100.0
- _hitokage_ version: 4a3a9f6369bb12214baaecc8ee76a30849597a9d

`init.lua`
```lua
local monitors = hitokage.monitor.get_all()

for _, monitor in ipairs(monitors) do
	monitor:attach({
		children = {
			{ Box = {} },
			{ Clock = { format = "%a %b %u %R", halign = "End" } },
		},
		homogeneous = true,
	})
end
```

`styles.css`
```css
window {
  /* Be careful about setting values here, this also modifies the debugger appearance */
  font-family: 'JetBrainsMono Nerd Font';
  font-size: 12px;
  color: #000000;
}

.bar {
  background-color: rgba(60, 56, 54, 0);
  color: #ffffe0;
  
  font-family: 'JetBrainsMono Nerd Font';
  font-size: 24px;
  line-height: 32px;
  min-height: 32px;
}

.workspace {
  background-color: rgba(60, 56, 54, 1);
  padding: 0px 0px 0px 8px;
  /* border: 1px solid rgba(255, 0, 0, 0.4); */
}

.workspacechild {
  /* distance between workspace children */
  /* margin-left: 8px; */
  border: 1px solid rgba(168, 153, 132, 0.4);

  color: #ffffe0;

  /* font-size: 12px; */
  line-height: 24px;

  transition: all 500ms;
  transition-property: min-width, background-color;
}

.workspacechild:first-child {
  margin-left: 0px;
}

.workspacechild:selected {
  /* min-width: 32px; */
  border: 1px solid #ffffe0;
  background-color: #ffffe0;
  color: rgba(60, 56, 54, 1.0);
  font-weight: bold;
}

.data {
  padding-right: 8px;
}

.bar-group {
  background-color: rgba(60, 56, 54, 1);
}

.bar-group.left {
  min-width: 160px;
  border-radius: 0px 12px 12px 0px;
}

.bar-group.center {
  margin-left: 8px;
  padding-left: 8px;
  padding-right: 8px;
  border-radius: 12px;
}

.bar-group.right {
  padding-left: 8px;
  padding-right: 8px;
  border-radius: 12px 0px 0px 12px;
}

.bar-group-extra {
  font-size: 20px;
  line-height: 24px;
  color: rgba(60, 56, 54, 1);
}

.fix-spacing {
  /* just centers the two elements in the center which aren't homogeneous */
  margin-left: 8px;
}

.icon {
  font-size: 20px;
  line-height: 20px;
  padding-top: 2px;
  padding-right: 8px;
  padding-bottom: 2px;
  padding-left: 8px;
  font-weight: bold;
}

/* .memory {
  color: #fff;
}

.cpu {
  color: #fff;
} */

/* .cpu.usage-10 {
  color: #00ff00;
}

.cpu.usage-20 {
  color: #ff0000;
} */
```

Recording of issue (running hitokage without komorebi, starting komorebi, then running hitokage again; it only starts the second time)
<img src="https://github.com/user-attachments/assets/d9b78a68-9bdd-4225-9b75-5bbadd699d30" width="400" />

Error log:
```
(hitokage.exe:21584): GLib-GIO-WARNING **: 12:00:50.881: win32 session dbus binary not found
2025-01-23T18:00:50.886Z INFO  [hitokage] attempting to load lua init.lua at: C:\Users\akami\.config/hitokage/init.lua
2025-01-23T18:00:50.886Z INFO  [hitokage] attempting to load lua styles.css at: C:\Users\akami\.config/hitokage/styles.css
2025-01-23T18:00:50.887Z INFO  [hitokage] Loading styles.css
thread 'main' panicked at hitokage\src\socket.rs:13:51:
Failed to open socket: Os { code: 10061, kind: ConnectionRefused, message: "No connection could be made because the target machine actively refused it." }
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'main' panicked at core\src\panicking.rs:221:5:
panic in a function that cannot unwind
stack backtrace:
   0:     0x7ff73e1c9fa1 - <unknown>
   1:     0x7ff73e1e3d4a - <unknown>
   2:     0x7ff73e1c5827 - <unknown>
   3:     0x7ff73e1c9de5 - <unknown>
   4:     0x7ff73e1cb917 - <unknown>
   5:     0x7ff73e1cb6f7 - <unknown>
   6:     0x7ff73e1cbfa3 - <unknown>
   7:     0x7ff73e1cbdf2 - <unknown>
   8:     0x7ff73e1ca6ef - <unknown>
   9:     0x7ff73e1cba2e - <unknown>
  10:     0x7ff73e265895 - <unknown>
  11:     0x7ff73e265943 - <unknown>
  12:     0x7ff73e265a25 - <unknown>
  13:     0x7ff73db75528 - <unknown>
  14:     0x7ff73e21c0c0 - <unknown>
  15:     0x7ff73e21b6b8 - <unknown>
  16:     0x7ffd4f543846 - RtlCaptureContext2
  17:     0x7ff73db7538d - <unknown>
  18:     0x7ffcf2a59980 - g_closure_invoke
  19:     0x7ffcf2a70828 - g_signal_stop_emission_by_name
  20:     0x7ffcf2a71a7e - g_signal_stop_emission_by_name
  21:     0x7ffcf2a6c7fc - g_signal_emit
  22:     0x7ffcf0e76835 - g_application_register
  23:     0x7ffcf0e764b0 - g_application_quit
  24:     0x7ffcf0e76b7f - g_application_run
  25:     0x7ff73db163df - <unknown>
  26:     0x7ff73db16538 - <unknown>
  27:     0x7ff73dafcc79 - <unknown>
  28:     0x7ff73dafc45f - <unknown>
  29:     0x7ff73db64e96 - <unknown>
  30:     0x7ff73db7558c - <unknown>
  31:     0x7ff73e1c041c - <unknown>
  32:     0x7ff73dafd3cc - <unknown>
  33:     0x7ff73e21894c - <unknown>
  34:     0x7ffd4e33e8d7 - BaseThreadInitThunk
  35:     0x7ffd4f4ffbcc - RtlUserThreadStart
thread caused non-unwinding panic. aborting.
```
